[package]
name = "serial-brain-rs"
version = "0.1.0"
description = "A Tauri App"
authors = ["Tao Yu"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "serial_brain_rs_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = "4.0"
rand = "0.8"
encoding_rs = "0.8"
image = "0.25.6"
base64 = "0.22.1"
sci-rs = "0.4.1"
tokio = { version = "1", features = ["full", "time"] }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
tauri-plugin-os = "2"
tauri-plugin-opener = "2"
tauri-plugin-fs = {version="2", features = ["watch"] }
tauri-plugin-dialog = "2"
tauri-plugin-android-forward-service = { path = "../tauri-plugin-android-forward-service" }
# opencv = { version = "0.94" }
